### ISSUE TITLE
Library Usage

### ISSUE THREAD

**Issue by ZephyrusMB** [MarketSquare/robotframework-openapidriver#10]
Hi, 
How can i pass params to a request? Es. from pet/{petId}  to pet/1 
How can i pass body to a POST?
What arguments do i have to pass to the test template keyword? can i add arguments to my keyword (es base url)?

Documentation to my point of view is not so clear on how maximize the advantage of this very interesting library.

Thank you very much 
 
This is how I used your library (following the tests example) and i'd like to test the get with parameters

`*** Settings ***
Library             OpenApiDriver
...                 source=petstore_openapi.yaml
#...                 origin=http://localhost:8080
...                 ignored_endpoints=${ignored_endpoints}
Library    RequestsLibrary
Library    Collections
Test Template       Execute Get   

*** Variables ***
@{ignored_endpoints}=
...                         /pet    /pet/findByStatus    /pet/findByTags    /store/inventory
...                             /store/order    /store/order/{orderId}    /pet/{petId}/uploadImage
...                         /user/createWithList    /user/login    /user/{username}  
${baseUrl}    http://localhost:8080/api/v3
*** Test Cases ***
openapi.json test for ${method} on ${endpoint} where ${status_code} is expected

*** Keywords ***
Execute Get
    # used this keyword for /store/inventory
    [Arguments]    ${endpoint}    ${method}    ${status_code}    #can i add base url?
    Log Dictionary    ${DataDriver_DATA_DICT}
    Log Dictionary    ${DataDriver_TEST_DATA}
    Log List        ${DataDriver_DATA_LIST}
    #Log    ${path}
    ${response}    GET            ${baseUrl}${endpoint}    
    Log    ${response.json()}
    

Execute Get With Params
    #trying to use it for the /pet/{petId}
    ${response}    GET   ${baseUrl}${endpoint}  params=1
    `

**Comment by robinmackaij** [comment]
Hello Matteo,

The idea / approach for OpenApiDriver is different from what you're trying to do. What the library will do is, based on the information in the openapi document, generate a test case for each endpoint + method + status_code. For each of these, it will automatically generated the required data (a valid url, valid parameters, valid body) based on the schema in the openapi document and then perform the operation.

If you want to get a feel for what's happening "in the background", what you could do is to use the `Test Endpoint` keyword in your `Test Template` and just let it run without ignoring any endpoints. In the logs, you'll be able to dig down into the keywords.  If you set the log level to `TRACE`, the Robot Framework will also log incoming parameters and return values for all keyword calls, so what you're trying to `Log` in your `Execute Get` keyword, is already being logged at TRACE level by the framework.
