### ISSUE TITLE
Requests with client certifications

### ISSUE THREAD

**Issue by rumiak** [MarketSquare/robotframework-openapidriver#25]
Hi Guys,

I would like to use OpenApiDriver in one of my API projects. Our API is protected with certificates. 

Is it possible to setup OpenApiDriver with certificates and keys store in PEM files as in case of Create Client Cert Session keyword from RequestLibrary?

**Comment by robinmackaij** [comment]
Sorry for the late response, I've missed the notification for this request. I've just added the support to OpenApiLibCore and OpenApiDriver (v3.4.0) by adding the `cert` parameter to the library parameters. It passes the path or cert tuple (see https://requests.readthedocs.io/en/latest/user/advanced/#client-side-certificates) with every request.
