### ISSUE TITLE
missing dependency for 'click'

### ISSUE THREAD

**Issue by leonpros** [MarketSquare/robotframework-openapidriver#26]
after installing robotframework-openapidriver, trying to run `prance `throws exception
`venv\lib\site-packages\prance\cli.py", line 9, in <module>
    import click`
after installing manually ['click'](https://pypi.org/project/click/), issue resolved

**Comment by robinmackaij** [comment]
What is the prance version that was installed? This looks like a dependency issue and it could be that I need to include some extras from prance.

**Comment by leonpros** [comment]
prance version:  0.22.11.4.0  
robotframework-openapidriver: 3.6.1

**Comment by robinmackaij** [comment]
I see that indeed click is a [CLI] dependency. I've never noticed this
since click is also a dependency of black (which is a dev dependency). I'll
update the prance dependency in the next release to also include the [CLI]
dependencies. Thanks for reporting this.

**Comment by robinmackaij** [comment]
Fixed in a previous release.
