### ISSUE TITLE
Validate response schema

### ISSUE THREAD

**Issue by leonpros** [MarketSquare/robotframework-openapidriver#28]
As i understand by documentation, this awesome idea for generating automated tests by openapi document has 2 major issues that by sound like a deal breaker for using it in automation project:
1. No response schema validation.
2. No negative response codes generated.

I believe that at least schema validation is really important.
Validating response code is simply not enough.

I really hope this feature can be developed

**Comment by robinmackaij** [comment]
Could you indicate which part of the documentation led you to this conclusion since both items are in fact being performed.
________________________________
From: leonpros ***@***.***>
Sent: Sunday, April 16, 2023 4:17:04 PM
To: MarketSquare/robotframework-openapidriver ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MarketSquare/robotframework-openapidriver] Validate response schema (Issue #28)


As i understand by documentation, this awesome idea for generating automated tests by openapi document has 2 major issues that by sound like a deal breaker for using it in automation project:

  1.  No response schema validation.
  2.  No negative response codes generated.

I believe that at least schema validation is really important.
Validating response code is simply not enough.

I really hope this feature can be developed

**Comment by leonpros** [comment]
I might be wrong, but this is how I understood it from documentation of [Test Endpoint](https://marketsquare.github.io/robotframework-openapidriver/openapidriver.html#Test%20Endpoint) keyword:
> "Validate that performing the method operation on endpoint results in a status_code response"

Regarding the negative response codes, how does the library generate tests with invalid data?
I am not talking about the [Test Unauthorized](https://marketsquare.github.io/robotframework-openapidriver/openapidriver.html#Test%20Unauthorized) keyword.

I would really want to use this library

**Comment by robinmackaij** [comment]
The status code is checked, but the Test Endpoint documentation also states:

> The keyword calls other keywords to generate the neccesary data to perform the desired operation and validate the response against the openapi document.

The exact checks that are being performed do need some documentation improvement, but checking the response against the response schema from the OAS is among them.

Basic 422 / 400 (if 422 is not used) invalidation can use a number of mechanics; a random property (from header, query or  body) is selected and invalidated (if possible). This can be by breaking a constraint (such as min / max value or length) or providing an invalid data type (e.g. a string where the OAS specifies an int).

For 4xx codes that rely on business rules, you can implement a mappings file:
https://marketsquare.github.io/robotframework-openapi-libcore/advanced_use.html

To get a feel of how the library works and see an example in action, you can take a look at the repo I made for the workshop I gave at RoboCon 2023:
https://github.com/robinmackaij/robocon-demo-api
(the task `inv run-tests` will run all suites)

You can also find a simple example for a mapping file that relates 2 resources types:
https://github.com/robinmackaij/robocon-demo-api/blob/main/excercises/mappings.py

Looking at the TRACE level log should give you a better idea of what checks are being performed.

Let me know if you have any more questions / suggestions!

**Comment by leonpros** [comment]
I am working on the mapping file since yesterday without luck. I used the only example i saw in the repo [custom_user_mappings.py](https://github.com/MarketSquare/robotframework-openapi-libcore/blob/main/tests/user_implemented/custom_user_mappings.py), but still didn't find the way to make it work fully.

I think you have a minor typo in documentation for "IdReference" [here](https://marketsquare.github.io/robotframework-openapi-libcore/advanced_use.html)
![image](https://user-images.githubusercontent.com/12122878/232466040-f665fdae-ec3a-451e-9850-49c13238ce2c.png)
The main issue i am dealing with at the moment is probably related to IdDependency/IdReference.
I will take a deep look into the link you've sent, thank you

**Comment by robinmackaij** [comment]
That indeed looks like a cut/paste error from my side. I'm plannning on a small release on Wednesday, I'll see about fixing that documentation error.

Feel free to contact me on the Robot Framework Slack if you want to chat / set up a call to discuss the details of the mappings.
________________________________

**Comment by robinmackaij** [comment]
Documentation was corrected in a previous release.
