### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by leonpros** [MarketSquare/robotframework-openapidriver#30]
openApi is now version 3+ on most new projects.
In the [getting-started](https://github.com/MarketSquare/robotframework-openapidriver#getting-started) part, `prance` is used to validate schema.
Default configuration will use `flex` for validating and it will fail with error since it is no longer updated:
>  [ValidationError]: Version mismatch: selected backend "flex" does not support specified version 3.0.1!

advised to use the following
`prance validate --backend=openapi-spec-validator https://domain.com/v3/api-docs`

**Comment by robinmackaij** [comment]
This is indeed an issue if `flex` is present in the Python environment (which was not the case in my repos). I've updated the docstring with your suggestion. This will become visible in the docs when I build a new release (which should be somewhere this week).
