### ISSUE TITLE
'Test cannot be empty' error with robot framewrok language server

### ISSUE THREAD

**Issue by Thibuko** [MarketSquare/robotframework-openapidriver#36]
If i use the example given in the README in VSCode, the robot framework language server gives me an syntax error on the line 
`Test Endpoint for ${method} on ${path} where ${status_code} is expected`

Same with robocop that gives 
`Test case 'Test Endpoint for ${method} on ${path} where ${status_code} is expected' has too few keywords inside`

It works at execution time, but I don't know how to get rid of theses error, it seems i can't handle dynamic data driven tests.  Any idea?

**Comment by robinmackaij** [comment]
I don't use `robot framework language server` myself, but if it reports a syntax error on that line that runs just fine, that's an issue in `robot framework language server` and you can report the issue in that repo:
https://github.com/robocorp/robotframework-lsp

The warning in `robocop` is just that; a warning. In most cases, having very few keywords within a test case or other keyword is an indication of low quality code (in this case; more indirection / layers than needed). For these types of generated data driven tests, those warning don't really apply / don't really make sense.

Now if you really would want to suppress that particular warning from robocop, you can do so:
https://robocop.readthedocs.io/en/1.12.0/including_rules.html#ignore-rule-from-source-code
