### ISSUE TITLE
release new version

### ISSUE THREAD

**Issue by Leemur89** [MarketSquare/robotframework-openapidriver#42]
Hello,
In the released version there are some bugs (I'm having a lot of failures) that have been fixed in the latest commits. Could you please trigger the release of a new version please? (also I've raised a PR that brings another fix, if that could be also included that would be great)
Thanks

**Comment by robinmackaij** [comment]
Hi @Leemur89, thanks for your PR and feedback!

With regards to the PR, I'll need some time to check on how `requests` handles empty dict vs None as json payload. I need to consider the situation where the OAS does allow for an empty dict (object without required properties) vs the body being nullable.

With regards to a release, I'm in the process of migrating this repo and openapi-libcore to robotframework-openapitools:
https://pypi.org/project/robotframework-openapitools/
I'm in the process of testing the changes to make the libraries work more smoothly with the `RobotCode` language server (and I did find an issue that I hope to address later this week).
Note that openapitools is an in-place replacement for openapidriver and openapi-libcore; you can `pip uninstall` them both and `pip install robotframework-openapitools` and things should run as before. That should include all the latest commits on openapidriver and openapi-libcore.

**Comment by Leemur89** [comment]
Thanks @robinmackaij , I'll move my PR to that new project
For the empty body, I've dug a bit deeper and ultimately the `json_data` variable get passed to the `request` method as `json` attribute which allows `None` as value (which is its default value):

From `openapi_libcore.py`:

```python
response = self.session.request(
    url=url,
    method=method,
    params=params,
    headers=headers,
    json=json_data,  # <----------
    cookies=self.cookies,
    auth=self.auth,
    proxies=self.proxies,
    verify=self.verify,
    cert=self.cert,
)
```

And the definition of the request method:

```python
    def request(
        self,
        method,
        url,
        params=None,
        data=None,
        headers=None,
        cookies=None,
        files=None,
        auth=None,
        timeout=None,
        allow_redirects=True,
        proxies=None,
        hooks=None,
        stream=None,
        verify=None,
        cert=None,
        json=None,  # <----------
    ):
```

**Comment by robinmackaij** [comment]
Yes, I know. My concern is that an OAS can define a body model with only optional properties. In that case, `{}` is a valid body. However, `if body else None` would change this to a post without a body, which would be a different situation. So I do see that always sending an empty dict as the body is not correct behavior, never sending an empty dict is also not correct. So the change to correct the behavior is a bit more involved and includes adding the appropriate tests (which may require an update to the testserver).

**Comment by Leemur89** [comment]
I've added an option when importing the lib -> https://github.com/MarketSquare/robotframework-openapitools/pull/1
